import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { X, PauseCircle, Ban, Workflow, CheckCircle2, RotateCcw, Archive, PlayCircle } from 'lucide-react';
import { Badge, Prioridad } from '../lib/ui.jsx';
import { useExpedientes } from '../context/ExpedienteContext.jsx';

export default function DetailDrawer({e,onClose,role='jefatura',actions=[],historical=false}){
 if(!e) return null;
 const jefe=role==='jefatura'; const navigate=useNavigate();
 const {anular,liberar,devolver,aprobar,cerrar,bloquear,enviarRevision}=useExpedientes();
 const [modal,setModal]=useState(null); const [text,setText]=useState('');
 const submit=()=>{ if(!text.trim()) return; if(modal==='anular') anular(e.id,text.trim()); if(modal==='devolver') devolver(e.id,text.trim()); if(modal==='liberar') liberar(e.id,text.trim()); if(modal==='bloquear') bloquear(e.id,'Esperando información',text.trim()); setModal(null);setText(''); };
 const actionItems=[];
 if(jefe){
   if(!historical) actionItems.push({label:'Ver en workflow',icon:<Workflow size={16}/>,onClick:()=>{onClose();navigate(`/workflow?expediente=${encodeURIComponent(e.id)}&drawer=closed`)}});
   if(e.estado==='En revisión'){
     actionItems.push({label:'Devolver a proceso',icon:<RotateCcw size={16}/>,onClick:()=>setModal('devolver')});
     actionItems.push({label:'Aprobar / Conforme',icon:<CheckCircle2 size={16}/>,primary:true,onClick:()=>aprobar(e.id)});
   }
   if(e.estado==='Aprobado / Conforme') actionItems.push({label:'Archivar / Cerrar',icon:<Archive size={16}/>,primary:true,onClick:()=>cerrar(e.id)});
   if(e.estado!=='Anulado' && e.estado!=='Archivado / Cerrado') actionItems.push({label:'Anular',icon:<Ban size={16}/>,danger:true,onClick:()=>setModal('anular')});
 } else {
   if(e.estado==='En proceso'){
     actionItems.push({label:'Bloquear',icon:<PauseCircle size={16}/>,onClick:()=>setModal('bloquear')});
     actionItems.push({label:'Enviar a revisión',icon:<CheckCircle2 size={16}/>,primary:true,onClick:()=>{const c=window.prompt('Comentario final para Jefatura (obligatorio):'); if(c?.trim()) enviarRevision(e.id,c.trim())}});
   }
   if(e.estado==='Bloqueado') actionItems.push({label:'Liberar bloqueo',icon:<PlayCircle size={16}/>,primary:true,onClick:()=>setModal('liberar')});
 }
 return <div className="fixed inset-0 z-50 bg-slate-900/30 backdrop-blur-[1px]" onMouseDown={onClose}><aside className="absolute right-0 top-0 h-full w-full max-w-xl overflow-y-auto bg-white shadow-2xl" onMouseDown={x=>x.stopPropagation()}>
   <div className="sticky top-0 z-10 border-b border-slate-200 bg-white/95 px-5 py-4 backdrop-blur"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="text-xs font-semibold uppercase tracking-wider text-verde-600">Detalle del expediente</div><div className="mt-1 flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold text-slate-900">{e.id}</h2><Badge>{e.estado}</Badge></div><p className="mt-1 text-sm text-slate-500">{e.encargo}</p><div className="mt-2 flex items-center gap-2 text-xs font-medium text-slate-500">Prioridad: <Prioridad>{e.prioridad}</Prioridad></div></div><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={20}/></button></div></div>
   <div className="space-y-5 p-5">
    {['Archivado / Cerrado','Anulado'].includes(e.estado) && <div className={`rounded-xl border p-4 ${e.estado==='Anulado'?'border-red-200 bg-red-50':'border-slate-200 bg-slate-50'}`}><div className="font-semibold text-slate-900">{e.estado==='Anulado'?'❌ Expediente anulado':'📁 Expediente archivado / cerrado'}</div><p className="mt-1 text-sm text-slate-600">Este expediente ya no requiere gestión operativa, pero conserva su historial completo para consulta.</p></div>}
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Solicitante',e.solicitante],['Responsable',e.responsable],['Solicitud',e.fechaSolicitud],['Compromiso',e.plazo]].map(([k,v])=><div key={k} className="rounded-xl border border-slate-200 bg-slate-50 p-3"><div className="text-[11px] font-medium uppercase text-slate-400">{k}</div><div className="mt-1 text-sm font-semibold text-slate-800">{v}</div></div>)}</div>
    {e.bloqueo && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="flex items-center gap-2 font-semibold text-amber-900"><PauseCircle size={17}/> Bloqueo</div><p className="mt-2 text-sm text-amber-900"><strong>{e.bloqueo.motivo}.</strong> {e.bloqueo.comentario}</p><p className="mt-2 text-xs text-amber-800">Inicio: {e.bloqueo.inicio}{e.bloqueo.fin && ` · Liberado: ${e.bloqueo.fin}`}</p>{e.bloqueo.liberacionComentario&&<p className="mt-2 text-xs text-amber-900"><strong>Liberación:</strong> {e.bloqueo.liberacionComentario}</p>}</div>}
    <section><h3 className="font-semibold text-slate-900">📋 Solicitud</h3><div className="mt-2 rounded-xl border border-slate-200 p-4 text-sm leading-6 text-slate-700">{e.encargo}</div></section>
    <section><h3 className="font-semibold text-slate-900">⏱ Seguimiento</h3><div className="mt-2 grid grid-cols-2 gap-2 text-center sm:grid-cols-4"><div className="rounded-xl bg-slate-50 p-3"><div className="text-xs text-slate-500">Solicitud</div><div className="mt-1 text-sm font-semibold">{e.fechaSolicitud}</div></div><div className="rounded-xl bg-slate-50 p-3"><div className="text-xs text-slate-500">Derivación</div><div className="mt-1 text-sm font-semibold">{e.fechaDerivacion || '—'}</div></div><div className="rounded-xl bg-slate-50 p-3"><div className="text-xs text-slate-500">Compromiso</div><div className="mt-1 text-sm font-semibold">{e.plazo}</div></div><div className="rounded-xl bg-verde-50 p-3"><div className="text-xs text-verde-700">Antigüedad</div><div className="mt-1 text-sm font-bold text-verde-800">{Math.max(0,Math.floor((new Date('2026-08-12T12:00:00')-new Date(`${e.fechaSolicitud}T12:00:00`))/86400000))} día{Math.max(0,Math.floor((new Date('2026-08-12T12:00:00')-new Date(`${e.fechaSolicitud}T12:00:00`))/86400000))===1?'':'s'}</div></div></div></section>
    <section><h3 className="font-semibold text-slate-900">💬 Comentarios</h3><div className="mt-2 space-y-2">{e.comentarios.length?e.comentarios.map((c,i)=><div key={i} className="rounded-xl border border-slate-200 bg-white p-3 text-sm text-slate-700">{c}</div>):<div className="text-sm text-slate-400">Sin comentarios registrados.</div>}</div></section>
    <section><h3 className="font-semibold text-slate-900">📜 Historial</h3><div className="mt-3 space-y-3">{e.historial.map((h,i)=><div key={i} className="flex gap-3"><div className="mt-1 h-2 w-2 shrink-0 rounded-full bg-verde-500"/><div><div className="text-sm font-medium text-slate-800">{h[1]}</div><div className="text-xs text-slate-500">{h[0]} · {h[2]}</div></div></div>)}</div></section>
    <div className="sticky bottom-0 -mx-5 border-t border-slate-200 bg-white px-5 py-4"><div className="flex flex-wrap gap-2">{[...actions,...actionItems].map((a,i)=><button key={i} onClick={a.onClick} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold ${a.danger?'border border-red-200 bg-red-50 text-red-700 hover:bg-red-100':a.primary?'bg-verde-600 text-white hover:bg-verde-700':'border border-slate-200 bg-white text-slate-700 hover:bg-slate-50'}`}>{a.icon}{a.label}</button>)}</div></div>
   </div></aside>
   {modal&&<div className="absolute inset-0 z-20 flex items-center justify-center bg-slate-900/25 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl" onMouseDown={x=>x.stopPropagation()}><h3 className="text-lg font-bold">{modal==='anular'?'❌ Anular expediente':modal==='liberar'?'▶️ Liberar bloqueo':modal==='bloquear'?'⏸️ Bloquear expediente':'↩️ Devolver a proceso'}</h3><p className="mt-2 text-sm text-slate-500">{modal==='liberar'?'¿Llegó el archivo? ¿Se recibió el antecedente? ¿Está todo listo para continuar?':modal==='bloquear'?'Ej.: ¿Qué antecedente estás esperando? ¿De quién depende? ¿Qué falta para poder continuar?':modal==='anular'?'Indique obligatoriamente el motivo de la anulación.':'Indique qué debe corregirse o revisarse.'}</p><textarea autoFocus value={text} onChange={e=>setText(e.target.value)} placeholder="Escriba el comentario..." className="mt-4 min-h-32 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-verde-500"/><div className="mt-4 flex justify-end gap-2"><button onClick={()=>{setModal(null);setText('')}} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold">Cancelar</button><button disabled={!text.trim()} onClick={submit} className="rounded-lg bg-verde-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-40">Confirmar</button></div></div></div>}
 </div>
}
