import { useState } from 'react';
import { Search, UserPlus, CheckCircle2, RotateCcw, Archive, Eye } from 'lucide-react';
import { useExpedientes } from '../context/ExpedienteContext.jsx';
import { PERSONAS } from '../fixtures/expedientes.js';
import { Badge, Prioridad } from '../lib/ui.jsx';
import DetailDrawer from '../components/DetailDrawer.jsx';
export default function Bandeja(){
 const {expedientes,asignar,aprobar,devolver,cerrar,anular}=useExpedientes(); const [q,setQ]=useState(''); const [sel,setSel]=useState(null);
 const asignarList=expedientes.filter(e=>e.estado==='Pendiente'&&(!q||`${e.id} ${e.solicitante} ${e.encargo}`.toLowerCase().includes(q.toLowerCase())));
 const gestion=expedientes.filter(e=>['En revisión','Aprobado / Conforme'].includes(e.estado)&&(!q||`${e.id} ${e.solicitante} ${e.encargo}`.toLowerCase().includes(q.toLowerCase())));
 const e=expedientes.find(x=>x.id===sel);
 const actions=e?[e.estado==='En revisión'?{label:'Devolver',icon:<RotateCcw size={16}/>,onClick:()=>{const c=window.prompt('Comentario obligatorio para la devolución:');if(c){devolver(e.id,c);setSel(null)}},primary:false}:{label:'Cerrar',icon:<Archive size={16}/>,onClick:()=>{cerrar(e.id);setSel(null)},primary:false}, e.estado==='En revisión'?{label:'Aprobar / Conforme',icon:<CheckCircle2 size={16}/>,onClick:()=>{aprobar(e.id);setSel(null)},primary:true}:{label:'Anular',icon:<Archive size={16}/>,onClick:()=>{const c=window.prompt('Motivo de anulación:');if(c){anular(e.id,c);setSel(null)}},primary:false}]:[];
 const Row=({x,assignMode})=><tr className="border-b border-slate-100 hover:bg-slate-50"><td className="px-4 py-3"><button onClick={()=>setSel(x.id)} className="font-semibold text-verde-700 hover:underline">{x.id}</button></td><td className="px-4 py-3">{x.solicitante}</td><td className="max-w-xs px-4 py-3 text-slate-600">{x.encargo}</td><td className="px-4 py-3"><Prioridad>{x.prioridad}</Prioridad></td><td className="px-4 py-3">{x.plazo}</td><td className="px-4 py-3">{assignMode?<div className="flex items-center gap-2"><select defaultValue="" onChange={ev=>ev.target.dataset.person=ev.target.value} className="rounded-lg border border-slate-200 px-2 py-2 text-xs"><option value="">Seleccionar</option>{PERSONAS.map(p=><option key={p}>{p}</option>)}</select><button onClick={ev=>{const p=ev.currentTarget.previousSibling.dataset.person;if(p){asignar(x.id,p)}}} className="inline-flex items-center gap-1 rounded-lg bg-verde-600 px-3 py-2 text-xs font-semibold text-white"><UserPlus size={14}/>Asignar</button></div>:<div className="flex gap-2"><button onClick={()=>setSel(x.id)} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold"><Eye size={14}/>Revisar</button>{x.estado==='En revisión'?<button onClick={()=>{aprobar(x.id)}} className="inline-flex items-center gap-1 rounded-lg bg-verde-600 px-3 py-2 text-xs font-semibold text-white"><CheckCircle2 size={14}/>Aprobar</button>:<button onClick={()=>cerrar(x.id)} className="inline-flex items-center gap-1 rounded-lg bg-verde-600 px-3 py-2 text-xs font-semibold text-white"><Archive size={14}/>Cerrar</button>}</div>}</td></tr>;
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-sm font-semibold text-verde-600">Jefatura</div><h1 className="text-2xl font-bold">📥 Bandeja</h1><p className="mt-1 text-sm text-slate-500">Todo lo que requiere una acción de Jefatura, visible al mismo tiempo.</p></div><div className="relative w-full sm:w-80"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar expediente, solicitante o encargo..." className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-9 pr-3 text-sm shadow-sm"/></div></div>
  <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-semibold">📤 Asignar <span className="ml-2 rounded-full bg-slate-100 px-2 py-1 text-xs">{asignarList.length}</span></h2><p className="text-sm text-slate-500">Pendientes de asignación.</p></div></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Expediente','Solicitante','Encargo','Prioridad','Compromiso','Acción'].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{asignarList.map(x=><Row key={x.id} x={x} assignMode/>)}{!asignarList.length&&<tr><td colSpan="6" className="p-8 text-center text-sm text-slate-500">No hay solicitudes pendientes de asignación.</td></tr>}</tbody></table></div></section>
  <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-semibold">👤 Mi gestión <span className="ml-2 rounded-full bg-violet-50 px-2 py-1 text-xs text-violet-700">{gestion.length}</span></h2><p className="text-sm text-slate-500">Expedientes que requieren una acción de Jefatura.</p></div></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Expediente','Solicitante','Encargo','Estado','Compromiso','Acción'].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{gestion.map(x=><tr key={x.id} className="border-b border-slate-100 hover:bg-slate-50"><td className="px-4 py-3"><button onClick={()=>setSel(x.id)} className="font-semibold text-verde-700 hover:underline">{x.id}</button></td><td className="px-4 py-3">{x.solicitante}</td><td className="max-w-xs px-4 py-3 text-slate-600">{x.encargo}</td><td className="px-4 py-3"><Badge>{x.estado}</Badge></td><td className="px-4 py-3">{x.plazo}</td><td className="px-4 py-3"><div className="flex gap-2"><button onClick={()=>setSel(x.id)} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold"><Eye size={14}/>Revisar</button>{x.estado==='En revisión'?<button onClick={()=>aprobar(x.id)} className="inline-flex items-center gap-1 rounded-lg bg-verde-600 px-3 py-2 text-xs font-semibold text-white"><CheckCircle2 size={14}/>Aprobar</button>:<button onClick={()=>cerrar(x.id)} className="inline-flex items-center gap-1 rounded-lg bg-verde-600 px-3 py-2 text-xs font-semibold text-white"><Archive size={14}/>Cerrar</button>}</div></td></tr>)}{!gestion.length&&<tr><td colSpan="6" className="p-8 text-center text-sm text-slate-500">No hay expedientes que requieran acción de Jefatura.</td></tr>}</tbody></table></div></section>
  {e&&<DetailDrawer e={e} onClose={()=>setSel(null)} role="jefatura" actions={actions}/>}</div>
}
