import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AlertTriangle, Clock3, PauseCircle, CheckCircle2, X, UserRound, Users } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, PieChart, Pie, Cell, Legend } from 'recharts';
import { useExpedientes } from '../context/ExpedienteContext.jsx';
import { Badge, Prioridad, ESTADOS, active } from '../lib/ui.jsx';
import DetailDrawer from '../components/DetailDrawer.jsx';
const today='2026-08-12';
export default function Dashboard(){
 const {expedientes}=useExpedientes(); const navigate=useNavigate(); const [filter,setFilter]=useState(null); const [person,setPerson]=useState(null); const [sel,setSel]=useState(null);
 const counts=Object.fromEntries(ESTADOS.map(s=>[s,expedientes.filter(e=>e.estado===s).length]));
 const atrasados=expedientes.filter(e=>active(e)&&e.plazo<today).length;
 const visible=expedientes.filter(e=>active(e)&&(!filter || filter==='Total' || (filter==='Atrasados'?e.plazo<today:e.estado===filter))&&(!person||e.responsable===person));
 const people=[...new Set(expedientes.map(e=>e.responsable).filter(p=>p&&p!=='Sin asignar'))];
 const data=people.map(nombre=>{const mine=visible.filter(e=>e.responsable===nombre); return {nombre:nombre.split(' ')[0],total:mine.length,'En proceso':mine.filter(e=>e.estado==='En proceso').length,'En revisión':mine.filter(e=>e.estado==='En revisión').length,'Bloqueado':mine.filter(e=>e.estado==='Bloqueado').length,'Pendiente':mine.filter(e=>e.estado==='Pendiente').length,'Aprobado':mine.filter(e=>e.estado==='Aprobado / Conforme').length};});
 const donut=ESTADOS.map(estado=>({estado,total:counts[estado]})).filter(x=>x.total>0);
 const goWorkflow=(params)=>navigate(`/workflow?${new URLSearchParams(params).toString()}`);
 const insights=[]; const hoy=expedientes.filter(e=>active(e)&&e.plazo===today).length; if(hoy) insights.push(['danger',`${hoy} expediente${hoy>1?'s tienen':' tiene'} compromiso para hoy.`,()=>goWorkflow({plazo:'hoy'})]); if(atrasados) insights.push(['danger',`${atrasados} expediente${atrasados>1?'s están':' está'} atrasado${atrasados>1?'s':''}.`,()=>goWorkflow({plazo:'atrasados'})]);
 const blocked=people.map(p=>({p,n:expedientes.filter(e=>e.responsable===p&&e.estado==='Bloqueado').length})).filter(x=>x.n).sort((a,b)=>b.n-a.n); if(blocked[0]) insights.push(['warn',`${blocked[0].p} tiene ${blocked[0].n} expediente${blocked[0].n>1?'s':''} bloqueado${blocked[0].n>1?'s':''}.`,()=>goWorkflow({estado:'Bloqueado',responsable:blocked[0].p})]);
 const cargas=people.map(p=>({p,n:expedientes.filter(e=>e.responsable===p&&active(e)).length})).sort((a,b)=>b.n-a.n); if(cargas[0]) insights.push(['warn',`${cargas[0].p} tiene la mayor carga: ${cargas[0].n} expedientes activos.`,()=>goWorkflow({responsable:cargas[0].p})]);
 const revision=expedientes.filter(e=>e.estado==='En revisión').length; if(revision) insights.push(['info',`Tienes ${revision} expediente${revision>1?'s':''} pendiente${revision>1?'s':''} de revisión.`,()=>goWorkflow({estado:'En revisión'})]);
 const card=(label,n,icon,cls,filterValue)=> <button onClick={()=>{setFilter(filter===filterValue?null:filterValue);setPerson(null)}} className={`rounded-xl border bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${filter===filterValue?'border-verde-500 ring-2 ring-verde-100':'border-slate-200'}`}><div className="flex items-center justify-between"><span className="text-sm font-medium text-slate-500">{label}</span><span className={`rounded-lg p-2 ${cls}`}>{icon}</span></div><div className="mt-3 text-2xl font-bold text-slate-900">{n}</div></button>;
 return <div className="space-y-6">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-sm font-semibold text-verde-600">Jefatura</div><h1 className="text-2xl font-bold tracking-tight">Dashboard</h1><p className="mt-1 text-sm text-slate-500">Una lectura rápida del estado, carga y situaciones que requieren atención.</p></div><div className="min-w-64 rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><label className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-slate-500"><Users size={15}/> Responsable</label><select value={person||''} onChange={e=>{setPerson(e.target.value||null);setFilter(null)}} className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm font-medium text-slate-700"><option value="">Todos los responsables</option>{people.map(p=><option key={p} value={p}>{p}</option>)}</select></div></div><div className="rounded-xl border border-verde-100 bg-verde-50 px-4 py-3"><span className="text-xs font-semibold uppercase tracking-wide text-verde-600">Visión</span><div className="mt-0.5 text-base font-bold text-verde-900">{person||'Todo el equipo'}</div></div>
  <div className="grid gap-4 md:grid-cols-2"><button onClick={()=>{setFilter(filter==='Total'?null:'Total');setPerson(null)}} className={`rounded-2xl border bg-verde-700 p-5 text-left text-white shadow-sm ${filter==='Total'?'ring-2 ring-verde-300':''}`}><div className="text-sm text-verde-100">Total</div><div className="mt-2 text-3xl font-bold">{expedientes.length}</div><div className="mt-1 text-xs text-verde-100">Todos los expedientes registrados</div></button>{card('Atrasados',atrasados,<AlertTriangle size={18}/>,'bg-red-50 text-red-700','Atrasados')}</div>
  <div><div className="mb-3 flex items-center justify-between"><div><h2 className="font-semibold text-slate-900">Estado del workflow</h2><p className="text-xs text-slate-500">Cada estado funciona como filtro del Dashboard.</p></div>{(filter||person)&&<button onClick={()=>{setFilter(null);setPerson(null)}} className="inline-flex items-center gap-1 text-xs font-semibold text-verde-700">Limpiar filtros <X size={13}/></button>}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{ESTADOS.map(s=>card(s,counts[s],s==='Bloqueado'?<PauseCircle size={18}/>:s==='En revisión'?<CheckCircle2 size={18}/>:<Clock3 size={18}/>,s==='Bloqueado'?'bg-amber-50 text-amber-800':s==='En revisión'?'bg-violet-50 text-violet-700':'bg-slate-100 text-slate-700',s))}</div></div>
  {(filter||person)&&<div className="flex flex-wrap items-center gap-2 rounded-xl border border-verde-200 bg-verde-50 px-4 py-3 text-sm"><span className="font-semibold text-verde-800">Filtro activo:</span>{filter&&<span className="rounded-full bg-white px-3 py-1 font-medium text-verde-800">{filter}</span>}{person&&<span className="rounded-full bg-white px-3 py-1 font-medium text-verde-800">{person}</span>}<button onClick={()=>{setFilter(null);setPerson(null)}} className="ml-auto text-xs font-semibold text-verde-700">Quitar filtros</button></div>}
  <section className="rounded-2xl border border-amber-200 bg-white shadow-sm"><div className="border-b border-amber-100 bg-amber-50/60 px-5 py-4"><h2 className="font-semibold text-slate-900">🔎 Atención y gestión</h2><p className="text-sm text-slate-500">Lectura rápida calculada directamente desde los datos del workflow. Cada aviso abre el Workflow con el filtro correspondiente.</p></div><div className="grid gap-3 p-4 md:grid-cols-2">{insights.map(([type,text,onClick],i)=><button key={i} onClick={onClick} className="rounded-xl border border-slate-200 bg-white p-4 text-left transition hover:border-verde-300 hover:bg-verde-50/40"><div className={`text-sm font-semibold ${type==='danger'?'text-red-700':type==='warn'?'text-amber-800':'text-blue-700'}`}>● {text}</div><div className="mt-1 text-xs text-slate-500">Ir al Workflow filtrado →</div></button>)}{!insights.length&&<div className="p-3 text-sm text-emerald-700">✓ No hay situaciones destacadas que requieran atención.</div>}</div></section>
  <div className="grid gap-6 lg:grid-cols-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:col-span-3"><div className="flex items-start justify-between"><div><h2 className="font-semibold">Carga por responsable</h2><p className="text-sm text-slate-500">Expedientes activos, segmentados por estado. Haz clic en una barra para filtrar.</p></div><UserRound size={19} className="text-slate-400"/></div><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} onClick={d=>{if(d?.activeLabel){const p=people.find(x=>x.startsWith(d.activeLabel));setPerson(p);setFilter(null)}}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="nombre"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="Pendiente" stackId="a" fill="#94a3b8" name="Pendiente"/><Bar dataKey="En proceso" stackId="a" fill="#60a5fa" name="En proceso"/><Bar dataKey="En revisión" stackId="a" fill="#a78bfa" name="En revisión"/><Bar dataKey="Bloqueado" stackId="a" fill="#f59e0b" name="Bloqueado"/><Bar dataKey="Aprobado" stackId="a" fill="#34d399" name="Aprobado / Conforme"/></BarChart></ResponsiveContainer></div></section>
   <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:col-span-2"><div><h2 className="font-semibold">Estado de los expedientes</h2><p className="text-sm text-slate-500">Distribución del total por estado. Haz clic en un segmento para ir al Workflow filtrado.</p></div><div className="mt-2 h-72"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={donut} dataKey="total" nameKey="estado" cx="50%" cy="45%" innerRadius={62} outerRadius={92} paddingAngle={2} onClick={(d)=>goWorkflow({estado:d.estado})}>{donut.map((_,i)=><Cell key={i} fill={['#94a3b8','#60a5fa','#f59e0b','#a78bfa','#34d399','#64748b','#ef4444'][i%7]}/>)}</Pie><Legend verticalAlign="bottom" height={52} wrapperStyle={{fontSize:12}}/><text x="50%" y="43%" textAnchor="middle" dominantBaseline="middle" className="fill-slate-900 text-2xl font-bold">{expedientes.length}</text><text x="50%" y="52%" textAnchor="middle" dominantBaseline="middle" className="fill-slate-500 text-xs">TOTAL</text><Tooltip/></PieChart></ResponsiveContainer></div></section>
  </div>
  <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold">Actividades recientes</h2><p className="text-sm text-slate-500">{visible.length} expedientes dentro del filtro actual.</p></div><div className="max-h-72 overflow-y-auto">{visible.slice(0,6).map(x=><button key={x.id} onClick={()=>setSel(x.id)} className="flex w-full gap-3 border-b border-slate-100 px-5 py-3 text-left hover:bg-slate-50"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-verde-500"/><span><span className="block text-sm font-semibold text-slate-800">{x.id} · {x.estado}</span><span className="block text-xs text-slate-500">{x.responsable} · {x.encargo}</span></span></button>)}{!visible.length&&<div className="p-5 text-sm text-slate-500">No hay actividades para este filtro.</div>}</div></section>
  {sel&&<DetailDrawer e={expedientes.find(x=>x.id===sel)} onClose={()=>setSel(null)} role="jefatura"/>}
 </div>
}
