import { useMemo, useState } from 'react';
import { Search, History, Filter } from 'lucide-react';
import { useExpedientes } from '../context/ExpedienteContext.jsx';
import { Badge, Prioridad } from '../lib/ui.jsx';
import DetailDrawer from '../components/DetailDrawer.jsx';

const TERMINALES=['Archivado / Cerrado','Anulado'];
export default function Historico(){
 const {expedientes,rol}=useExpedientes(); const jefe=rol==='jefatura'; const [estado,setEstado]=useState('Todos'); const [persona,setPersona]=useState('Todos'); const [q,setQ]=useState(''); const [sel,setSel]=useState(null);
 const personas=['Todos',...new Set(expedientes.map(e=>e.responsable).filter(Boolean))];
 const participo=(e,nombre)=>e.responsable===nombre||e.historial?.some(h=>h[2]===nombre);
 const historico=useMemo(()=>expedientes.filter(e=>TERMINALES.includes(e.estado)&&(!jefe||persona==='Todos'||participo(e,persona))&&(!q||`${e.id} ${e.encargo} ${e.solicitante} ${e.responsable}`.toLowerCase().includes(q.toLowerCase()))&&(estado==='Todos'||(estado==='Anulado'&&e.estado==='Anulado')||(estado==='Archivado / Cerrado'&&e.estado==='Archivado / Cerrado'))),[expedientes,jefe,persona,q,estado]);
 const total=expedientes.filter(e=>TERMINALES.includes(e.estado)&&(jefe||participo(e,'Juan Pérez'))).length;
 const count=s=>expedientes.filter(e=>e.estado===s&&(jefe||participo(e,'Juan Pérez'))).length;
 return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-sm font-semibold text-verde-600">{jefe?'Jefatura · Todo el equipo':'Responsable · Juan Pérez'}</div><h1 className="text-2xl font-bold">📚 Histórico</h1><p className="mt-1 text-sm text-slate-500">Expedientes finalizados que ya no requieren gestión operativa, pero conservan toda su trazabilidad.</p></div><div className="relative w-full sm:w-80"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar expediente..." className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-9 pr-3 text-sm"/></div></div>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Kpi label="Todos" value={total} active={estado==='Todos'} onClick={()=>setEstado('Todos')}/><Kpi label="Archivado / Cerrado" value={count('Archivado / Cerrado')} active={estado==='Archivado / Cerrado'} onClick={()=>setEstado('Archivado / Cerrado')}/><Kpi label="Anulados" value={count('Anulado')} tone="red" active={estado==='Anulado'} onClick={()=>setEstado('Anulado')}/><div className="rounded-xl border border-slate-200 bg-white p-4"><div className="text-xs text-slate-500">Visión</div><div className="mt-1 text-sm font-semibold text-slate-800">{jefe?(persona==='Todos'?'Todo el equipo':persona):'Mi trabajo histórico'}</div></div></div>
 <div className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm md:grid-cols-2"><label className="text-xs font-semibold text-slate-500">Estado histórico<select value={estado} onChange={e=>setEstado(e.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option>Todos</option><option value="Archivado / Cerrado">Archivado / Cerrado</option><option value="Anulado">Anulado</option></select></label>{jefe&&<label className="text-xs font-semibold text-slate-500">Responsable<select value={persona} onChange={e=>setPersona(e.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">{personas.map(p=><option key={p}>{p}</option>)}</select></label>}</div>
 <div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-100 px-4 py-3 text-sm font-semibold text-slate-700"><History size={16}/> Expedientes históricos <span className="ml-auto text-xs font-medium text-slate-400">{historico.length} resultados</span></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Expediente','Responsable','Prioridad','Fecha solicitud','Estado'].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{historico.map(e=><tr key={e.id} onClick={()=>setSel(e.id)} className={`cursor-pointer border-b border-slate-100 hover:bg-slate-50 ${sel===e.id?'bg-verde-50':''}`}><td className="px-4 py-4"><span className="font-semibold text-verde-700">{e.id}</span><div className="mt-1 max-w-md text-xs text-slate-500">{e.encargo}</div></td><td className="px-4 py-4">{e.responsable}</td><td className="px-4 py-4"><Prioridad>{e.prioridad}</Prioridad></td><td className="px-4 py-4">{e.fechaSolicitud}</td><td className="px-4 py-4"><Badge>{e.estado}</Badge></td></tr>)}</tbody></table></div></div>
 {sel&&<DetailDrawer e={expedientes.find(x=>x.id===sel)} onClose={()=>setSel(null)} role={rol} historical/>}</div>
}
function Kpi({label,value,tone='green',active,onClick}){return <button onClick={onClick} className={`rounded-xl border bg-white p-4 text-left ${active?'border-verde-400 ring-2 ring-verde-100':'border-slate-200'}`}><div className="text-xs text-slate-500">{label}</div><div className={`mt-1 text-2xl font-bold ${tone==='red'?'text-red-700':'text-slate-900'}`}>{value}</div></button>}
