import { useState } from 'react';
import { Search, PauseCircle, Send, PlayCircle } from 'lucide-react';
import { useExpedientes } from '../context/ExpedienteContext.jsx';
import { Badge, Prioridad } from '../lib/ui.jsx';
import DetailDrawer from '../components/DetailDrawer.jsx';

export default function MisExpedientes(){
 const {expedientes,bloquear,liberar,enviarRevision}=useExpedientes();
 const [sel,setSel]=useState(null); const [q,setQ]=useState(''); const [modal,setModal]=useState(null); const [filter,setFilter]=useState('Todos');
 const lista=expedientes.filter(e=>e.responsable==='Juan Pérez'&&['En proceso','Bloqueado','En revisión'].includes(e.estado)&&(!q||`${e.id} ${e.encargo}`.toLowerCase().includes(q.toLowerCase())));
 const atrasados=lista.filter(x=>new Date(x.plazo+'T23:59:59')<new Date('2026-08-12T12:00:00'));
 const base=lista.filter(x=>filter==='Todos'||(filter==='Atrasados'?atrasados.some(a=>a.id===x.id):x.estado===filter));
 const e=expedientes.find(x=>x.id===sel);
 const doBlock=()=>{if(modal?.motivo&&modal?.comentario){bloquear(e.id,modal.motivo,modal.comentario);setModal(null)}};
 const release=()=>{const c=window.prompt('Comentario de liberación (obligatorio): ¿Llegó el archivo? ¿Se recibió el antecedente? ¿Está todo listo para continuar?');if(c?.trim())liberar(e.id,c.trim())};
 return <div className="space-y-5">
  <div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-sm font-semibold text-verde-600">Responsable · Juan Pérez</div><h1 className="text-2xl font-bold">👤 Mi bandeja</h1><p className="mt-1 text-sm text-slate-500">Expedientes asignados a mí y acciones disponibles según su estado.</p></div><div className="relative w-full sm:w-80"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input value={q} onChange={x=>setQ(x.target.value)} placeholder="Buscar expediente..." className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-9 pr-3 text-sm"/></div></div>
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
   <Kpi label="Total" value={lista.length} active={filter==='Todos'} onClick={()=>setFilter('Todos')}/>
   <Kpi label="Bloqueados" value={lista.filter(x=>x.estado==='Bloqueado').length} tone="amber" active={filter==='Bloqueado'} onClick={()=>setFilter('Bloqueado')}/>
   <Kpi label="En revisión" value={lista.filter(x=>x.estado==='En revisión').length} tone="violet" active={filter==='En revisión'} onClick={()=>setFilter('En revisión')}/>
   <Kpi label="Atrasados" value={atrasados.length} tone="red" active={filter==='Atrasados'} onClick={()=>setFilter('Atrasados')}/>
  </div>
  {filter!=='Todos'&&<div className="rounded-xl border border-verde-200 bg-verde-50 px-4 py-3 text-sm"><span className="font-semibold text-verde-800">Filtro activo:</span> {filter}<button onClick={()=>setFilter('Todos')} className="ml-3 font-semibold text-verde-700 hover:underline">Limpiar</button></div>}
  <div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Expediente','Encargo','Prioridad','Compromiso','Estado','Acción'].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{base.map(x=><tr key={x.id} className="border-b border-slate-100 hover:bg-slate-50"><td className="px-4 py-4"><button onClick={()=>setSel(x.id)} className="font-semibold text-verde-700 hover:underline">{x.id}</button></td><td className="max-w-md px-4 py-4 text-slate-600">{x.encargo}</td><td className="px-4 py-4"><Prioridad>{x.prioridad}</Prioridad></td><td className="px-4 py-4">{x.plazo}</td><td className="px-4 py-4"><Badge>{x.estado}</Badge></td><td className="px-4 py-4"><div className="flex flex-wrap gap-2">{x.estado==='En proceso'&&<><button onClick={()=>{setSel(x.id);setModal({motivo:'',comentario:''})}} className="inline-flex items-center gap-1 rounded-lg border border-amber-200 px-3 py-2 text-xs font-semibold text-amber-800"><PauseCircle size={14}/>Bloquear</button><button onClick={()=>{const c=window.prompt('Comentario final para Jefatura (obligatorio):');if(c?.trim())enviarRevision(x.id,c.trim())}} className="inline-flex items-center gap-1 rounded-lg bg-verde-600 px-3 py-2 text-xs font-semibold text-white"><Send size={14}/>Enviar a revisión</button></>}{x.estado==='Bloqueado'&&<button onClick={()=>{setSel(x.id);release()}} className="inline-flex items-center gap-1 rounded-lg bg-verde-600 px-3 py-2 text-xs font-semibold text-white"><PlayCircle size={14}/>Liberar bloqueo</button>}</div></td></tr>)}</tbody></table></div></div>
  {e&&<DetailDrawer e={e} onClose={()=>{setSel(null);setModal(null)}} role="responsable" actions={e.estado==='En proceso'?[{label:'Bloquear',icon:<PauseCircle size={16}/>,onClick:()=>setModal({motivo:'',comentario:''})},{label:'Enviar a revisión',icon:<Send size={16}/>,onClick:()=>{const c=window.prompt('Comentario final para Jefatura (obligatorio):');if(c?.trim()){enviarRevision(e.id,c.trim());setSel(null)}},primary:true}]:e.estado==='Bloqueado'?[{label:'Liberar bloqueo',icon:<PlayCircle size={16}/>,onClick:()=>{release();setSel(null)},primary:true}]:[]} />}
  {modal&&<div className="fixed inset-0 z-[60] grid place-items-center bg-slate-900/40 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl"><h2 className="text-lg font-bold">⏸️ Bloquear expediente</h2><label className="mt-4 block text-sm font-semibold">Motivo<select value={modal.motivo} onChange={e=>setModal({...modal,motivo:e.target.value})} className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5"><option value="">Seleccionar motivo</option><option>Esperando antecedentes</option><option>Esperando información</option><option>Esperando respuesta de otra persona/área</option><option>Observación pendiente de resolver</option><option>Dependencia externa</option><option>Otro</option></select></label><label className="mt-4 block text-sm font-semibold">Comentario<textarea value={modal.comentario} onChange={e=>setModal({...modal,comentario:e.target.value})} rows="5" placeholder="Ej.: ¿Qué antecedente estás esperando? ¿De quién depende? ¿Qué falta para continuar? ¿Tienes una fecha estimada?" className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5"/></label><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setModal(null)} className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold">Cancelar</button><button disabled={!modal.motivo||!modal.comentario.trim()} onClick={doBlock} className="rounded-lg bg-verde-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Bloquear expediente</button></div></div></div>}
 </div>
}
function Kpi({label,value,tone='green',active,onClick}){const toneClass={green:'text-slate-900',amber:'text-amber-700',violet:'text-violet-700',red:'text-red-700'}[tone];return <button onClick={onClick} className={`rounded-xl border bg-white p-4 text-left ${active?'border-verde-400 ring-2 ring-verde-100':'border-slate-200'}`}><div className="text-xs text-slate-500">{label}</div><div className={`mt-1 text-2xl font-bold ${toneClass}`}>{value}</div></button>}
