import { useEffect, useState } from 'react';
import { Search, List, LayoutGrid, X } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { useExpedientes } from '../context/ExpedienteContext.jsx';
import { Badge, Prioridad, ESTADOS } from '../lib/ui.jsx';
import DetailDrawer from '../components/DetailDrawer.jsx';
export default function Workflow(){
 const {expedientes}=useExpedientes(); const [params,setParams]=useSearchParams(); const [q,setQ]=useState(params.get('q')||''); const [estado,setEstado]=useState(params.get('estado')||'Todos'); const [persona,setPersona]=useState(params.get('responsable')||'Todos'); const [view,setView]=useState('kanban'); const [sel,setSel]=useState(params.get('expediente')||null);
 useEffect(()=>{setQ(params.get('q')||'');setEstado(params.get('estado')||'Todos');setPersona(params.get('responsable')||'Todos');if(params.get('expediente'))setSel(params.get('expediente'));},[params]);
 const sync=(next)=>{const p=new URLSearchParams(); if(next.q) p.set('q',next.q); if(next.estado&&next.estado!=='Todos')p.set('estado',next.estado); if(next.responsable&&next.responsable!=='Todos')p.set('responsable',next.responsable); if(next.expediente)p.set('expediente',next.expediente); setParams(p)};
 const personas=['Todos',...new Set(expedientes.map(e=>e.responsable))]; const filtered=expedientes.filter(e=>!['Archivado / Cerrado','Anulado'].includes(e.estado)&&(estado==='Todos'||e.estado===estado)&&(persona==='Todos'||e.responsable===persona)&&(!q||`${e.id} ${e.encargo} ${e.solicitante}`.toLowerCase().includes(q.toLowerCase()))); const cols=['Pendiente','En proceso','Bloqueado','En revisión','Aprobado / Conforme']; const selected=expedientes.find(x=>x.id===sel); const drawerOpen=params.get('drawer')!=='closed';
 return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-sm font-semibold text-verde-600">Jefatura</div><h1 className="text-2xl font-bold">📊 Workflow</h1><p className="mt-1 text-sm text-slate-500">Vista global de dónde está cada expediente dentro del proceso.</p></div><div className="flex gap-2"><button onClick={()=>setView('kanban')} className={`rounded-lg border p-2 ${view==='kanban'?'bg-verde-50 text-verde-700':'bg-white'}`}><LayoutGrid size={17}/></button><button onClick={()=>setView('list')} className={`rounded-lg border p-2 ${view==='list'?'bg-verde-50 text-verde-700':'bg-white'}`}><List size={17}/></button></div></div>
 <div className="grid gap-2 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm md:grid-cols-3"><div className="relative"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input value={q} onChange={e=>{setQ(e.target.value);sync({q:e.target.value,estado, responsable:persona})}} placeholder="Buscar..." className="w-full rounded-lg border border-slate-200 py-2.5 pl-9 pr-3 text-sm"/></div><select value={estado} onChange={e=>{setEstado(e.target.value);sync({q,estado:e.target.value,responsable:persona})}} className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option>Todos</option>{ESTADOS.map(s=><option key={s}>{s}</option>)}</select><select value={persona} onChange={e=>{setPersona(e.target.value);sync({q,estado,responsable:e.target.value})}} className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm">{personas.map(s=><option key={s}>{s}</option>)}</select></div>
 {(estado!=='Todos'||persona!=='Todos'||q)&&<div className="flex flex-wrap items-center gap-2 rounded-xl border border-verde-200 bg-verde-50 px-4 py-3 text-sm"><span className="font-semibold text-verde-800">Filtros activos:</span>{q&&<span className="rounded-full bg-white px-3 py-1">{q}</span>}{estado!=='Todos'&&<span className="rounded-full bg-white px-3 py-1">Estado: {estado}</span>}{persona!=='Todos'&&<span className="rounded-full bg-white px-3 py-1">Responsable: {persona}</span>}<button onClick={()=>{setQ('');setEstado('Todos');setPersona('Todos');setSel(null);setParams({})}} className="ml-auto inline-flex items-center gap-1 text-xs font-semibold text-verde-700">Limpiar <X size={13}/></button></div>}
 {view==='kanban'?<div className="grid gap-4 overflow-x-auto lg:grid-cols-5">{cols.map(c=><div key={c} className="min-w-[230px] rounded-2xl border border-slate-200 bg-slate-50 p-3"><div className="flex items-center justify-between"><Badge>{c}</Badge><span className="text-xs font-bold text-slate-500">{filtered.filter(e=>e.estado===c).length}</span></div><div className="mt-3 space-y-2">{filtered.filter(e=>e.estado===c).map(e=><button key={e.id} onClick={()=>{setSel(e.id);sync({q,estado,responsable:persona,expediente:e.id})}} className={`w-full rounded-xl border p-3 text-left shadow-sm hover:border-verde-300 ${sel===e.id?'border-verde-500 ring-2 ring-verde-100':'border-slate-200 bg-white'}`}><div className="flex items-center justify-between"><span className="font-semibold text-verde-700">{e.id}</span><Prioridad>{e.prioridad}</Prioridad></div><div className="mt-2 text-xs text-slate-600">{e.responsable}</div><div className="mt-1 text-xs text-slate-500">Compromiso: {e.plazo}</div></button>)}</div></div>)}</div>:<div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Expediente','Responsable','Solicitud','Compromiso','Prioridad','Estado'].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{filtered.map(e=><tr key={e.id} onClick={()=>{setSel(e.id);sync({q,estado,responsable:persona,expediente:e.id})}} className={`cursor-pointer border-b border-slate-100 hover:bg-slate-50 ${sel===e.id?'bg-verde-50':''}`}><td className="px-4 py-3 font-semibold text-verde-700">{e.id}</td><td className="px-4 py-3">{e.responsable}</td><td className="px-4 py-3">{e.fechaSolicitud}</td><td className="px-4 py-3">{e.plazo}</td><td className="px-4 py-3"><Prioridad>{e.prioridad}</Prioridad></td><td className="px-4 py-3"><Badge>{e.estado}</Badge></td></tr>)}</tbody></table></div>}
 {selected&&drawerOpen&&<DetailDrawer e={selected} onClose={()=>{setSel(null);const p=new URLSearchParams(params);p.delete('expediente');setParams(p)}} role="jefatura"/>}</div>
}
